version: 0.2

phases:
  install:
    commands:
      - echo Installing necessary dependencies..
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip
      - unzip terraform_install.zip -d /usr/bin/
      - chmod +x /usr/bin/terraform
      - cd /usr/bin/
      - pwd
  pre_build:
    commands:
      - echo Installing source dependencies...
  build:
    commands:
#      - echo Build started.....
#      - echo $"export PATH=\$PATH:$(pwd)" >> ~/.bash_profile
#      - echo $PATH
#      - source ~/.bash_profile
#      - cd "$CODEBUILD_SRC_DIR"
#      - terraform --version
      - terraform init
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "Terraform script completed on `date`"
      - echo Build completed
artifacts:
  files:
    - '**/*'