version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Installing necessary dependencies..
      - wget https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      - pwd
      - ls
      - sudo yum install unzip
      - unzip terraform_0.12.18_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - pwd
      - terraform --version
  pre_build:
    commands:
      - echo Installing source dependencies...
  build:
    commands:
      - echo Build started.....
      - echo $"export PATH=\$PATH:$(pwd)" >> ~/.bash_profile
      - echo $PATH
      - source ~/.bash_profile
      - cd "$CODEBUILD_SRC_DIR"
      - terraform --version
      - terraform init
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "Terraform script completed on `date`"
      - echo Build completed
artifacts:
  files:
    - '**/*'