version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Installing necessary dependencies..
      - cd /usr/bin
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
      - unzip terraform.zip
      - pwd
      - ls -lrt
  pre_build:
    commands:
      - echo Installing source dependencies...
  build:
    commands:
      - echo Build started.....
      - echo $"export PATH=\$PATH:$(pwd)" >> ~/.bash_profile
      - echo $PATH
      - source ~/.bash_profile
      - python --version
      - pwd
      - terraform init
      - terraform apply -input=false -auto-approve
  post_build:
    commands:
      - echo "Terraform script completed on `date`"
      - echo Build completed
artifacts:
  files:
    - '**/*'